export default () => ({
  patientAlerts: [],
  patientMeta: {},
  patientAlertLoading: false,
  alerts: [],
  meta: {},
  types: [],
  isalertsLoading: false,
  isAction: false,
  histories: [],
  actions: [],
  historyLoading: false,
  people: [],
  /** for showing loader on add form */
  isCreating: false,
  createError: {},
  /** for closing drawer */
  isCreated: false,
  escalation: {},
  isEscLoading: false,
  escaltionId: "",
  pdfLink: "",
  contacts: [],
  genratingAction: false,
  actionTaken: false,
  closeAlert: null,
  isIdCorrect: false,
  checkingRef: false,
  refError: "",
  patientDot: false,
  /** for all  alert list */
  alertDot:false,
  reff_id:0,
});
