export default {
  successMsg: null,
  errorPatientVitals: null,
  patientVitalsLoader: false,
  buttonLoader: false,

  deviceTypes: [],
  reviewStatus: [],
  // vitalComments: [],
  vitalStatus: [],
  vitalFeelingStatus: [],
  vitalFields: [],
  glucoseRangeVitalFields: [],
  glucoseVitalFieldsDropdown: [],
  
  graphsListMeta: null,
  patientVitalsTable: [],
  patientBloodPressureGraph: [],
  patientHeartRateGraph: [],
  patientOxygenSaturationGraph: [],
  patientGlucoseGraph: [],
  patientLatestVitals: [],
  patientsVitalDetails: null,
  vitalTabs:null,
  vitalTypeValue:5,
  endParams: '&page=1',
  addVitalDefaults: null,
  getBPVitalDefaults: null,
  getBPBaselineValues: null,
  getOxygenVitalDefaults: null,
  getOxygenBaselineValues: null,
  getHeartRateVitalDefaults: null,
  getHeartRateBaselineValues: null,
  getGlucoseVitalDefaults: null,
  defaultPatientVitals: null,
  downloadVitals: null,
  glucoseVitalsRanges: [],
  glucoseVitalDefaultsList: [],
  localGlucoseVitalsRanges: [],
  patientVitalId: null,
}